
package com.ccb.simasc.ws.pagoCasoSimasc.impl;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

import com.ccb.simasc.ws.pagoCasoSimasc.CrearPagoCasoFault;
import com.ccb.simasc.ws.pagoCasoSimasc.CrearPagoCasoReqType;
import com.ccb.simasc.ws.pagoCasoSimasc.CrearPagoCasoRespType;
import com.ccb.simasc.ws.pagoCasoSimasc.ObjectFactory;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.7-b01-
 * Generated source version: 2.1
 * 
 */
@WebService(targetNamespace = "http://services.simasc/PagoCasoSimascWS")
@SOAPBinding(style = SOAPBinding.Style.DOCUMENT, use = SOAPBinding.Use.LITERAL, parameterStyle = SOAPBinding.ParameterStyle.BARE)
@XmlSeeAlso({ObjectFactory.class})
public interface PagoCasoSimascWS {


	/**
     * 
     * @param crearPagoCasoRequest
     * @return
     *     returns com.ccb.simasc.ws.pagoCasoSimasc.CrearPagoCasoRespType
     * @throws CrearPagoCasoFault
     */
    @WebMethod
    @WebResult(name = "CrearPagoCasoResponse", targetNamespace = "http://services.simasc/PagoCasoSimascSchema", partName = "CrearPagoCasoResponse")
    public CrearPagoCasoRespType crearPagoCaso(
        @WebParam(name = "CrearPagoCasoRequest", targetNamespace = "http://services.simasc/PagoCasoSimascSchema", partName = "CrearPagoCasoRequest")
        CrearPagoCasoReqType crearPagoCasoRequest)
        throws CrearPagoCasoFault;

}
