
package com.ccb.simasc.ws.pagoCasoSimasc;

import javax.xml.ws.WebFault;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.7-b01-
 * Generated source version: 2.1
 * 
 */
@WebFault(name = "CrearPagoCasoFault", targetNamespace = "http://services.simasc")
public class CrearPagoCasoFault
    extends Exception
{

    /**
     * Java type that goes as soapenv:Fault detail element.
     * 
     */
    private CrearPagoCasoFaultType faultInfo;

    /**
     * 
     * @param faultInfo
     * @param message
     */
    public CrearPagoCasoFault(String message, CrearPagoCasoFaultType faultInfo) {
        super(message);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @param faultInfo
     * @param cause
     * @param message
     */
    public CrearPagoCasoFault(String message, CrearPagoCasoFaultType faultInfo, Throwable cause) {
        super(message, cause);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @return
     *     returns fault bean: com.ccb.simasc.ws.pagoCasoSimasc.CrearPagoCasoFaultType
     */
    public CrearPagoCasoFaultType getFaultInfo() {
        return faultInfo;
    }

}
