
package com.ccb.simasc.ws.pagoCasoSimasc;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.7-b01-
 * Generated source version: 2.1
 * 
 */
@WebService(name = "PagoCasoSimascWS", targetNamespace = "http://services.simasc")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
@XmlSeeAlso({
    ObjectFactory.class
})
public interface PagoCasoSimascWS {


    /**
     * 
     * @param crearPagoCasoRequest
     * @return
     *     returns com.ccb.simasc.ws.pagoCasoSimasc.CrearPagoCasoRespType
     * @throws CrearPagoCasoFault
     */
    @WebMethod
    @WebResult(name = "CrearPagoCasoResponse", targetNamespace = "http://services.simasc", partName = "CrearPagoCasoResponse")
    public CrearPagoCasoRespType crearPagoCaso(
        @WebParam(name = "CrearPagoCasoRequest", targetNamespace = "http://services.simasc", partName = "CrearPagoCasoRequest")
        CrearPagoCasoReqType crearPagoCasoRequest)
        throws CrearPagoCasoFault
    ;

}
