
package com.ccb.simasc.ws.pagoCasoSimasc;

import java.net.MalformedURLException;
import java.net.URL;
import java.util.logging.Logger;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;


/**
 * Permite realizar la creacion de una solicitud de servicio de conciliacion en el sistema SIMASC con los datos basicos de la solicitud, entregando como resultado un mensaje, junto con el id del servicio creado en el sistema SIMASC.
 * 
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.7-b01-
 * Generated source version: 2.1
 * 
 */
@WebServiceClient(name = "PagoCasoSimascWS", targetNamespace = "http://services.simasc", wsdlLocation = "file:/C:/CCB/workspace-conciliacion/Branches/SimascConciliacion/SimascServiciosWeb/src/main/webapp/wsdl/PagoCasoSimascWS.wsdl")
public class PagoCasoSimascWS_Service
    extends Service
{

    private final static URL PAGOCASOSIMASCWS_WSDL_LOCATION;
    private final static Logger logger = Logger.getLogger(com.ccb.simasc.ws.pagoCasoSimasc.PagoCasoSimascWS_Service.class.getName());

    static {
        URL url = null;
        try {
            URL baseUrl;
            baseUrl = com.ccb.simasc.ws.pagoCasoSimasc.PagoCasoSimascWS_Service.class.getResource(".");
            url = new URL(baseUrl, "file:/C:/CCB/workspace-conciliacion/Branches/SimascConciliacion/SimascServiciosWeb/src/main/webapp/wsdl/PagoCasoSimascWS.wsdl");
        } catch (MalformedURLException e) {
            logger.warning("Failed to create URL for the wsdl Location: 'file:/C:/CCB/workspace-conciliacion/Branches/SimascConciliacion/SimascServiciosWeb/src/main/webapp/wsdl/PagoCasoSimascWS.wsdl', retrying as a local file");
            logger.warning(e.getMessage());
        }
        PAGOCASOSIMASCWS_WSDL_LOCATION = url;
    }

    public PagoCasoSimascWS_Service(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public PagoCasoSimascWS_Service() {
        super(PAGOCASOSIMASCWS_WSDL_LOCATION, new QName("http://services.simasc", "PagoCasoSimascWS"));
    }

    /**
     * 
     * @return
     *     returns PagoCasoSimascWS
     */
    @WebEndpoint(name = "PagoCasoSimascWSPort")
    public PagoCasoSimascWS getPagoCasoSimascWSPort() {
        return super.getPort(new QName("http://services.simasc", "PagoCasoSimascWSPort"), PagoCasoSimascWS.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns PagoCasoSimascWS
     */
    @WebEndpoint(name = "PagoCasoSimascWSPort")
    public PagoCasoSimascWS getPagoCasoSimascWSPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://services.simasc", "PagoCasoSimascWSPort"), PagoCasoSimascWS.class, features);
    }

}
