
package co.org.ccb.sirep2.clientes.ws;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;
import co.org.ccb.sirep2.clientes.ws.model.ActualizarClienteDatosContactoInDTO;
import co.org.ccb.sirep2.clientes.ws.model.ActualizarClienteDatosContactoOutDTO;
import co.org.ccb.sirep2.clientes.ws.model.BuscarInscritosWSInDTO;
import co.org.ccb.sirep2.clientes.ws.model.ConsultarDatosBasicosClienteWSInDTO;
import co.org.ccb.sirep2.clientes.ws.model.ConsultarDatosBasicosClienteWSOutDTO;
import co.org.ccb.sirep2.clientes.ws.model.ConsultarHomonimiaWSInDTO;
import co.org.ccb.sirep2.clientes.ws.model.ConsultarHomonimiaWSOutDTO;
import co.org.ccb.sirep2.clientes.ws.model.CrearClienteDatosContactoInDTO;
import co.org.ccb.sirep2.clientes.ws.model.CrearClienteDatosContactoOutDTO;
import co.org.ccb.sirep2.clientes.ws.model.ValidarProfesionLiberalOutDTO;
import co.org.ccb.sirep2.clientes.ws.model.ValidarRolCoordinadorOutDTO;
import co.org.ccb.sirep2.clientes.ws.model.VerificacionNitInDTO;
import co.org.ccb.sirep2.clientes.ws.model.VerificacionNitOutDTO;
import co.org.ccb.sirep2.clientes.ws.model.VerificacionPreRutInDTO;
import co.org.ccb.sirep2.clientes.ws.model.VerificacionPreRutOutDTO;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "ServiciosClientesWS", targetNamespace = "http://ws.clientes.sirep2.ccb.org.co")
@XmlSeeAlso({
    co.org.ccb.sirep2.clientes.ws.ObjectFactory.class,
    co.org.ccb.sirep2.clientes.ws.model.ObjectFactory.class
})
public interface ServiciosClientesWS {


    /**
     * 
     * @param inDto
     * @return
     *     returns co.org.ccb.sirep2.clientes.ws.ArrayOf5774855523488661NillableBuscarInscritosWSOutDTO
     */
    @WebMethod(action = "buscarInscritos")
    @WebResult(name = "buscarInscritosReturn", targetNamespace = "")
    @RequestWrapper(localName = "buscarInscritos", targetNamespace = "http://ws.clientes.sirep2.ccb.org.co", className = "co.org.ccb.sirep2.clientes.ws.BuscarInscritos")
    @ResponseWrapper(localName = "buscarInscritosResponse", targetNamespace = "http://ws.clientes.sirep2.ccb.org.co", className = "co.org.ccb.sirep2.clientes.ws.BuscarInscritosResponse")
    public ArrayOf5774855523488661NillableBuscarInscritosWSOutDTO buscarInscritos(
        @WebParam(name = "inDto", targetNamespace = "")
        BuscarInscritosWSInDTO inDto);

    /**
     * 
     * @param inDto
     * @return
     *     returns co.org.ccb.sirep2.clientes.ws.model.VerificacionPreRutOutDTO
     */
    @WebMethod(action = "verificacionPreRut")
    @WebResult(name = "verificacionPreRutReturn", targetNamespace = "")
    @RequestWrapper(localName = "verificacionPreRut", targetNamespace = "http://ws.clientes.sirep2.ccb.org.co", className = "co.org.ccb.sirep2.clientes.ws.VerificacionPreRut")
    @ResponseWrapper(localName = "verificacionPreRutResponse", targetNamespace = "http://ws.clientes.sirep2.ccb.org.co", className = "co.org.ccb.sirep2.clientes.ws.VerificacionPreRutResponse")
    public VerificacionPreRutOutDTO verificacionPreRut(
        @WebParam(name = "inDto", targetNamespace = "")
        VerificacionPreRutInDTO inDto);

    /**
     * 
     * @param inDto
     * @return
     *     returns co.org.ccb.sirep2.clientes.ws.model.VerificacionNitOutDTO
     */
    @WebMethod(action = "verificacionNit")
    @WebResult(name = "verificacionNitReturn", targetNamespace = "")
    @RequestWrapper(localName = "verificacionNit", targetNamespace = "http://ws.clientes.sirep2.ccb.org.co", className = "co.org.ccb.sirep2.clientes.ws.VerificacionNit")
    @ResponseWrapper(localName = "verificacionNitResponse", targetNamespace = "http://ws.clientes.sirep2.ccb.org.co", className = "co.org.ccb.sirep2.clientes.ws.VerificacionNitResponse")
    public VerificacionNitOutDTO verificacionNit(
        @WebParam(name = "inDto", targetNamespace = "")
        VerificacionNitInDTO inDto);

    /**
     * 
     * @param inDto
     * @return
     *     returns co.org.ccb.sirep2.clientes.ws.model.ConsultarHomonimiaWSOutDTO
     */
    @WebMethod(action = "consultarHomonimia")
    @WebResult(name = "consultarHomonimiaReturn", targetNamespace = "")
    @RequestWrapper(localName = "consultarHomonimia", targetNamespace = "http://ws.clientes.sirep2.ccb.org.co", className = "co.org.ccb.sirep2.clientes.ws.ConsultarHomonimia")
    @ResponseWrapper(localName = "consultarHomonimiaResponse", targetNamespace = "http://ws.clientes.sirep2.ccb.org.co", className = "co.org.ccb.sirep2.clientes.ws.ConsultarHomonimiaResponse")
    public ConsultarHomonimiaWSOutDTO consultarHomonimia(
        @WebParam(name = "inDto", targetNamespace = "")
        ConsultarHomonimiaWSInDTO inDto);

    /**
     * 
     * @param matricula
     * @return
     *     returns co.org.ccb.sirep2.clientes.ws.model.ValidarProfesionLiberalOutDTO
     */
    @WebMethod(action = "validarProfesionLiberal")
    @WebResult(name = "validarProfesionLiberalReturn", targetNamespace = "")
    @RequestWrapper(localName = "validarProfesionLiberal", targetNamespace = "http://ws.clientes.sirep2.ccb.org.co", className = "co.org.ccb.sirep2.clientes.ws.ValidarProfesionLiberal")
    @ResponseWrapper(localName = "validarProfesionLiberalResponse", targetNamespace = "http://ws.clientes.sirep2.ccb.org.co", className = "co.org.ccb.sirep2.clientes.ws.ValidarProfesionLiberalResponse")
    public ValidarProfesionLiberalOutDTO validarProfesionLiberal(
        @WebParam(name = "matricula", targetNamespace = "")
        String matricula);

    /**
     * 
     * @param matricula
     * @return
     *     returns co.org.ccb.sirep2.clientes.ws.model.ValidarRolCoordinadorOutDTO
     */
    @WebMethod(action = "validarRolCoordinador")
    @WebResult(name = "validarRolCoordinadorReturn", targetNamespace = "")
    @RequestWrapper(localName = "validarRolCoordinador", targetNamespace = "http://ws.clientes.sirep2.ccb.org.co", className = "co.org.ccb.sirep2.clientes.ws.ValidarRolCoordinador")
    @ResponseWrapper(localName = "validarRolCoordinadorResponse", targetNamespace = "http://ws.clientes.sirep2.ccb.org.co", className = "co.org.ccb.sirep2.clientes.ws.ValidarRolCoordinadorResponse")
    public ValidarRolCoordinadorOutDTO validarRolCoordinador(
        @WebParam(name = "matricula", targetNamespace = "")
        String matricula);

    /**
     * 
     * @param inDto
     * @return
     *     returns co.org.ccb.sirep2.clientes.ws.model.ConsultarDatosBasicosClienteWSOutDTO
     */
    @WebMethod(action = "consultarDatosBasicosCliente")
    @WebResult(name = "consultarDatosBasicosClienteReturn", targetNamespace = "")
    @RequestWrapper(localName = "consultarDatosBasicosCliente", targetNamespace = "http://ws.clientes.sirep2.ccb.org.co", className = "co.org.ccb.sirep2.clientes.ws.ConsultarDatosBasicosCliente")
    @ResponseWrapper(localName = "consultarDatosBasicosClienteResponse", targetNamespace = "http://ws.clientes.sirep2.ccb.org.co", className = "co.org.ccb.sirep2.clientes.ws.ConsultarDatosBasicosClienteResponse")
    public ConsultarDatosBasicosClienteWSOutDTO consultarDatosBasicosCliente(
        @WebParam(name = "inDto", targetNamespace = "")
        ConsultarDatosBasicosClienteWSInDTO inDto);

    /**
     * 
     * @param inDto
     * @return
     *     returns co.org.ccb.sirep2.clientes.ws.model.CrearClienteDatosContactoOutDTO
     */
    @WebMethod(action = "crearClienteDatosContacto")
    @WebResult(name = "crearClienteDatosContactoReturn", targetNamespace = "")
    @RequestWrapper(localName = "crearClienteDatosContacto", targetNamespace = "http://ws.clientes.sirep2.ccb.org.co", className = "co.org.ccb.sirep2.clientes.ws.CrearClienteDatosContacto")
    @ResponseWrapper(localName = "crearClienteDatosContactoResponse", targetNamespace = "http://ws.clientes.sirep2.ccb.org.co", className = "co.org.ccb.sirep2.clientes.ws.CrearClienteDatosContactoResponse")
    public CrearClienteDatosContactoOutDTO crearClienteDatosContacto(
        @WebParam(name = "inDto", targetNamespace = "")
        CrearClienteDatosContactoInDTO inDto);

    /**
     * 
     * @param inDto
     * @return
     *     returns co.org.ccb.sirep2.clientes.ws.model.ActualizarClienteDatosContactoOutDTO
     */
    @WebMethod(action = "actualizarClienteDatosContacto")
    @WebResult(name = "actualizarClienteDatosContactoReturn", targetNamespace = "")
    @RequestWrapper(localName = "actualizarClienteDatosContacto", targetNamespace = "http://ws.clientes.sirep2.ccb.org.co", className = "co.org.ccb.sirep2.clientes.ws.ActualizarClienteDatosContacto")
    @ResponseWrapper(localName = "actualizarClienteDatosContactoResponse", targetNamespace = "http://ws.clientes.sirep2.ccb.org.co", className = "co.org.ccb.sirep2.clientes.ws.ActualizarClienteDatosContactoResponse")
    public ActualizarClienteDatosContactoOutDTO actualizarClienteDatosContacto(
        @WebParam(name = "inDto", targetNamespace = "")
        ActualizarClienteDatosContactoInDTO inDto);

}
