//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.2-147 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.06.08 at 01:52:41 PM COT 
//


package com.ccb.simasc.transversal.dto.pup.generado;

import java.math.BigInteger;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{http://softwaresci.com/ceet/contabilizador/servicios}LibroId"/>
 *         &lt;element ref="{http://softwaresci.com/ceet/contabilizador/servicios}ActoId"/>
 *         &lt;element ref="{http://softwaresci.com/ceet/contabilizador/servicios}ImpuestoId"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "libroId",
    "actoId",
    "impuestoId"
})
@XmlRootElement(name = "Acto")
public class Acto {

    @XmlElement(name = "LibroId", required = true)
    protected BigInteger libroId;
    @XmlElement(name = "ActoId", required = true)
    protected BigInteger actoId;
    @XmlElement(name = "ImpuestoId", required = true)
    protected BigInteger impuestoId;

    /**
     * Gets the value of the libroId property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getLibroId() {
        return libroId;
    }

    /**
     * Sets the value of the libroId property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setLibroId(BigInteger value) {
        this.libroId = value;
    }

    /**
     * Gets the value of the actoId property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getActoId() {
        return actoId;
    }

    /**
     * Sets the value of the actoId property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setActoId(BigInteger value) {
        this.actoId = value;
    }

    /**
     * Gets the value of the impuestoId property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getImpuestoId() {
        return impuestoId;
    }

    /**
     * Sets the value of the impuestoId property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setImpuestoId(BigInteger value) {
        this.impuestoId = value;
    }

}
