//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.2-147 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.06.08 at 01:52:41 PM COT 
//


package com.ccb.simasc.transversal.dto.pup.generado;

import java.math.BigInteger;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{http://softwaresci.com/ceet/contabilizador/servicios}NumMatricula"/>
 *         &lt;element ref="{http://softwaresci.com/ceet/contabilizador/servicios}Moneda"/>
 *         &lt;element ref="{http://softwaresci.com/ceet/contabilizador/servicios}ValorTotal"/>
 *         &lt;element ref="{http://softwaresci.com/ceet/contabilizador/servicios}ArrayOfDetalleLiquidacionDto"/>
 *         &lt;element ref="{http://softwaresci.com/ceet/contabilizador/servicios}ActosVigencia"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "numMatricula",
    "moneda",
    "valorTotal",
    "arrayOfDetalleLiquidacionDto",
    "actosVigencia"
})
@XmlRootElement(name = "Detalle", namespace = "http://softwaresci.com/ccb/pupx/dto")
public class Detalle {

    @XmlElement(name = "NumMatricula", required = true)
    protected String numMatricula;
    @XmlElement(name = "Moneda", required = true)
    protected String moneda;
    @XmlElement(name = "ValorTotal", required = true)
    protected BigInteger valorTotal;
    @XmlElement(name = "ArrayOfDetalleLiquidacionDto", required = true)
    protected ArrayOfDetalleLiquidacionDto arrayOfDetalleLiquidacionDto;
    @XmlElement(name = "ActosVigencia", required = true)
    protected ActosVigencia actosVigencia;

    /**
     * Gets the value of the numMatricula property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNumMatricula() {
        return numMatricula;
    }

    /**
     * Sets the value of the numMatricula property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNumMatricula(String value) {
        this.numMatricula = value;
    }

    /**
     * Gets the value of the moneda property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMoneda() {
        return moneda;
    }

    /**
     * Sets the value of the moneda property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMoneda(String value) {
        this.moneda = value;
    }

    /**
     * Gets the value of the valorTotal property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getValorTotal() {
        return valorTotal;
    }

    /**
     * Sets the value of the valorTotal property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setValorTotal(BigInteger value) {
        this.valorTotal = value;
    }

    /**
     * Gets the value of the arrayOfDetalleLiquidacionDto property.
     * 
     * @return
     *     possible object is
     *     {@link ArrayOfDetalleLiquidacionDto }
     *     
     */
    public ArrayOfDetalleLiquidacionDto getArrayOfDetalleLiquidacionDto() {
        return arrayOfDetalleLiquidacionDto;
    }

    /**
     * Sets the value of the arrayOfDetalleLiquidacionDto property.
     * 
     * @param value
     *     allowed object is
     *     {@link ArrayOfDetalleLiquidacionDto }
     *     
     */
    public void setArrayOfDetalleLiquidacionDto(ArrayOfDetalleLiquidacionDto value) {
        this.arrayOfDetalleLiquidacionDto = value;
    }

    /**
     * Gets the value of the actosVigencia property.
     * 
     * @return
     *     possible object is
     *     {@link ActosVigencia }
     *     
     */
    public ActosVigencia getActosVigencia() {
        return actosVigencia;
    }

    /**
     * Sets the value of the actosVigencia property.
     * 
     * @param value
     *     allowed object is
     *     {@link ActosVigencia }
     *     
     */
    public void setActosVigencia(ActosVigencia value) {
        this.actosVigencia = value;
    }

}
