//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.2-147 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.06.08 at 01:52:41 PM COT 
//


package com.ccb.simasc.transversal.dto.pup.generado;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{http://softwaresci.com/ceet/contabilizador/servicios}AnoRenova"/>
 *         &lt;element ref="{http://softwaresci.com/ceet/contabilizador/servicios}ActoId"/>
 *         &lt;element ref="{http://softwaresci.com/ceet/contabilizador/servicios}Cantidad"/>
 *         &lt;element ref="{http://softwaresci.com/ceet/contabilizador/servicios}GastoAdministrativo"/>
 *         &lt;element ref="{http://softwaresci.com/ceet/contabilizador/servicios}Item"/>
 *         &lt;element ref="{http://softwaresci.com/ceet/contabilizador/servicios}ItemPadre"/>
 *         &lt;element ref="{http://softwaresci.com/ceet/contabilizador/servicios}LibroId"/>
 *         &lt;element ref="{http://softwaresci.com/ceet/contabilizador/servicios}Matricula"/>
 *         &lt;element ref="{http://softwaresci.com/ceet/contabilizador/servicios}Servicio"/>
 *         &lt;element ref="{http://softwaresci.com/ceet/contabilizador/servicios}ServicioId"/>
 *         &lt;element ref="{http://softwaresci.com/ceet/contabilizador/servicios}ServicioPadreId"/>
 *         &lt;element ref="{http://softwaresci.com/ceet/contabilizador/servicios}ValorTotal"/>
 *         &lt;element ref="{http://softwaresci.com/ceet/contabilizador/servicios}ValorBase"/>
 *         &lt;element ref="{http://softwaresci.com/ceet/contabilizador/servicios}CntPersonal"/>
 *         &lt;element ref="{http://softwaresci.com/ceet/contabilizador/servicios}FechaBase"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "anoRenova",
    "actoId",
    "cantidad",
    "gastoAdministrativo",
    "item",
    "itemPadre",
    "libroId",
    "matricula",
    "servicio",
    "servicioId",
    "servicioPadreId",
    "valorTotal",
    "valorBase",
    "cntPersonal",
    "fechaBase"
})
@XmlRootElement(name = "DetalleLiquidacionDto")
public class DetalleLiquidacionDto {

    @XmlElement(name = "AnoRenova", required = true)
    protected String anoRenova;
    @XmlElement(name = "ActoId", required = true)
    protected Integer actoId;
    @XmlElement(name = "Cantidad", required = true)
    protected Integer cantidad;
    @XmlElement(name = "GastoAdministrativo", required = true)
    protected String gastoAdministrativo;
    @XmlElement(name = "Item", required = true)
    protected Integer item;
    @XmlElement(name = "ItemPadre", required = true)
    protected Integer itemPadre;
    @XmlElement(name = "LibroId", required = true)
    protected Integer libroId;
    @XmlElement(name = "Matricula", required = true)
    protected String matricula;
    @XmlElement(name = "Servicio", required = true)
    protected String servicio;
    @XmlElement(name = "ServicioId", required = true)
    protected String servicioId;
    @XmlElement(name = "ServicioPadreId", required = true)
    protected String servicioPadreId;
    @XmlElement(name = "ValorTotal", required = true)
    protected Integer valorTotal;
    @XmlElement(name = "ValorBase", required = true)
    protected Integer valorBase;
    @XmlElement(name = "CntPersonal", required = true)
    protected String cntPersonal;
    @XmlElement(name = "FechaBase", required = true)
    protected String fechaBase;

    /**
     * Gets the value of the anoRenova property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAnoRenova() {
        return anoRenova;
    }

    /**
     * Sets the value of the anoRenova property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAnoRenova(String value) {
        this.anoRenova = value;
    }

    /**
     * Gets the value of the actoId property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getActoId() {
        return actoId;
    }

    /**
     * Sets the value of the actoId property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setActoId(Integer value) {
        this.actoId = value;
    }

    /**
     * Gets the value of the cantidad property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getCantidad() {
        return cantidad;
    }

    /**
     * Sets the value of the cantidad property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setCantidad(Integer value) {
        this.cantidad = value;
    }

    /**
     * Gets the value of the gastoAdministrativo property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getGastoAdministrativo() {
        return gastoAdministrativo;
    }

    /**
     * Sets the value of the gastoAdministrativo property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setGastoAdministrativo(String value) {
        this.gastoAdministrativo = value;
    }

    /**
     * Gets the value of the item property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getItem() {
        return item;
    }

    /**
     * Sets the value of the item property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setItem(Integer value) {
        this.item = value;
    }

    /**
     * Gets the value of the itemPadre property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getItemPadre() {
        return itemPadre;
    }

    /**
     * Sets the value of the itemPadre property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setItemPadre(Integer value) {
        this.itemPadre = value;
    }

    /**
     * Gets the value of the libroId property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getLibroId() {
        return libroId;
    }

    /**
     * Sets the value of the libroId property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setLibroId(Integer value) {
        this.libroId = value;
    }

    /**
     * Gets the value of the matricula property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMatricula() {
        return matricula;
    }

    /**
     * Sets the value of the matricula property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMatricula(String value) {
        this.matricula = value;
    }

    /**
     * Gets the value of the servicio property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getServicio() {
        return servicio;
    }

    /**
     * Sets the value of the servicio property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setServicio(String value) {
        this.servicio = value;
    }

    /**
     * Gets the value of the servicioId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getServicioId() {
        return servicioId;
    }

    /**
     * Sets the value of the servicioId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setServicioId(String value) {
        this.servicioId = value;
    }

    /**
     * Gets the value of the servicioPadreId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getServicioPadreId() {
        return servicioPadreId;
    }

    /**
     * Sets the value of the servicioPadreId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setServicioPadreId(String value) {
        this.servicioPadreId = value;
    }

    /**
     * Gets the value of the valorTotal property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getValorTotal() {
        return valorTotal;
    }

    /**
     * Sets the value of the valorTotal property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setValorTotal(Integer value) {
        this.valorTotal = value;
    }

    /**
     * Gets the value of the valorBase property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getValorBase() {
        return valorBase;
    }

    /**
     * Sets the value of the valorBase property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setValorBase(Integer value) {
        this.valorBase = value;
    }

    /**
     * Gets the value of the cntPersonal property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCntPersonal() {
        return cntPersonal;
    }

    /**
     * Sets the value of the cntPersonal property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCntPersonal(String value) {
        this.cntPersonal = value;
    }

    /**
     * Gets the value of the fechaBase property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFechaBase() {
        return fechaBase;
    }

    /**
     * Sets the value of the fechaBase property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFechaBase(String value) {
        this.fechaBase = value;
    }

}
