//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.2-147 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.06.08 at 01:52:41 PM COT 
//


package com.ccb.simasc.transversal.dto.pup.generado;

import java.math.BigInteger;
import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.generado package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _LibroId_QNAME = new QName("http://softwaresci.com/ceet/contabilizador/servicios", "LibroId");
    private final static QName _MonedaId_QNAME = new QName("http://softwaresci.com/ccb/pupx/dto", "MonedaId");
    private final static QName _Cantidad_QNAME = new QName("http://softwaresci.com/ceet/contabilizador/servicios", "Cantidad");
    private final static QName _ItemPadre_QNAME = new QName("http://softwaresci.com/ceet/contabilizador/servicios", "ItemPadre");
    private final static QName _ImpuestoId_QNAME = new QName("http://softwaresci.com/ceet/contabilizador/servicios", "ImpuestoId");
    private final static QName _OrigenIdDocumento_QNAME = new QName("http://softwaresci.com/ceet/contabilizador/servicios", "OrigenIdDocumento");
    private final static QName _Moneda_QNAME = new QName("http://softwaresci.com/ceet/contabilizador/servicios", "Moneda");
    private final static QName _CntPersonal_QNAME = new QName("http://softwaresci.com/ceet/contabilizador/servicios", "CntPersonal");
    private final static QName _ServicioPadreId_QNAME = new QName("http://softwaresci.com/ceet/contabilizador/servicios", "ServicioPadreId");
    private final static QName _ActoId_QNAME = new QName("http://softwaresci.com/ceet/contabilizador/servicios", "ActoId");
    private final static QName _IndicadorEspecial_QNAME = new QName("http://softwaresci.com/ceet/contabilizador/servicios", "IndicadorEspecial");
    private final static QName _AnoRenova_QNAME = new QName("http://softwaresci.com/ceet/contabilizador/servicios", "AnoRenova");
    private final static QName _Servicio_QNAME = new QName("http://softwaresci.com/ceet/contabilizador/servicios", "Servicio");
    private final static QName _GastoAdministrativo_QNAME = new QName("http://softwaresci.com/ceet/contabilizador/servicios", "GastoAdministrativo");
    private final static QName _NumMatricula_QNAME = new QName("http://softwaresci.com/ceet/contabilizador/servicios", "NumMatricula");
    private final static QName _Item_QNAME = new QName("http://softwaresci.com/ceet/contabilizador/servicios", "Item");
    private final static QName _ValorBase_QNAME = new QName("http://softwaresci.com/ceet/contabilizador/servicios", "ValorBase");
    private final static QName _Mensaje_QNAME = new QName("http://softwaresci.com/ccb/pupx/dto", "Mensaje");
    private final static QName _ErrorId_QNAME = new QName("http://softwaresci.com/ccb/pupx/dto", "ErrorId");
    private final static QName _Matricula_QNAME = new QName("http://softwaresci.com/ceet/contabilizador/servicios", "Matricula");
    private final static QName _ValorTotal_QNAME = new QName("http://softwaresci.com/ceet/contabilizador/servicios", "ValorTotal");
    private final static QName _FechaBase_QNAME = new QName("http://softwaresci.com/ceet/contabilizador/servicios", "FechaBase");
    private final static QName _ServicioId_QNAME = new QName("http://softwaresci.com/ceet/contabilizador/servicios", "ServicioId");
    private final static QName _FechaDocumentobroId_QNAME = new QName("http://softwaresci.com/ceet/contabilizador/servicios", "FechaDocumentobroId");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.generado
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link ArrayOfDetalleLiquidacionDto }
     * 
     */
    public ArrayOfDetalleLiquidacionDto createArrayOfDetalleLiquidacionDto() {
        return new ArrayOfDetalleLiquidacionDto();
    }

    /**
     * Create an instance of {@link ActosVigencia }
     * 
     */
    public ActosVigencia createActosVigencia() {
        return new ActosVigencia();
    }

    /**
     * Create an instance of {@link ActoVigencia }
     * 
     */
    public ActoVigencia createActoVigencia() {
        return new ActoVigencia();
    }

    /**
     * Create an instance of {@link Acto }
     * 
     */
    public Acto createActo() {
        return new Acto();
    }

    /**
     * Create an instance of {@link Actos }
     * 
     */
    public Actos createActos() {
        return new Actos();
    }

    /**
     * Create an instance of {@link Detalle }
     * 
     */
    public Detalle createDetalle() {
        return new Detalle();
    }

    /**
     * Create an instance of {@link RealizarLiquidacionResult }
     * 
     */
    public RealizarLiquidacionResult createRealizarLiquidacionResult() {
        return new RealizarLiquidacionResult();
    }

    /**
     * Create an instance of {@link RealizarLiquidacionResponse }
     * 
     */
    public RealizarLiquidacionResponse createRealizarLiquidacionResponse() {
        return new RealizarLiquidacionResponse();
    }

    /**
     * Create an instance of {@link DetalleLiquidacionDto }
     * 
     */
    public DetalleLiquidacionDto createDetalleLiquidacionDto() {
        return new DetalleLiquidacionDto();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigInteger }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://softwaresci.com/ceet/contabilizador/servicios", name = "LibroId")
    public JAXBElement<BigInteger> createLibroId(BigInteger value) {
        return new JAXBElement<BigInteger>(_LibroId_QNAME, BigInteger.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://softwaresci.com/ccb/pupx/dto", name = "MonedaId")
    public JAXBElement<String> createMonedaId(String value) {
        return new JAXBElement<String>(_MonedaId_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigInteger }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://softwaresci.com/ceet/contabilizador/servicios", name = "Cantidad")
    public JAXBElement<BigInteger> createCantidad(BigInteger value) {
        return new JAXBElement<BigInteger>(_Cantidad_QNAME, BigInteger.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigInteger }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://softwaresci.com/ceet/contabilizador/servicios", name = "ItemPadre")
    public JAXBElement<BigInteger> createItemPadre(BigInteger value) {
        return new JAXBElement<BigInteger>(_ItemPadre_QNAME, BigInteger.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigInteger }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://softwaresci.com/ceet/contabilizador/servicios", name = "ImpuestoId")
    public JAXBElement<BigInteger> createImpuestoId(BigInteger value) {
        return new JAXBElement<BigInteger>(_ImpuestoId_QNAME, BigInteger.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://softwaresci.com/ceet/contabilizador/servicios", name = "OrigenIdDocumento")
    public JAXBElement<String> createOrigenIdDocumento(String value) {
        return new JAXBElement<String>(_OrigenIdDocumento_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://softwaresci.com/ceet/contabilizador/servicios", name = "Moneda")
    public JAXBElement<String> createMoneda(String value) {
        return new JAXBElement<String>(_Moneda_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://softwaresci.com/ceet/contabilizador/servicios", name = "CntPersonal")
    public JAXBElement<String> createCntPersonal(String value) {
        return new JAXBElement<String>(_CntPersonal_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://softwaresci.com/ceet/contabilizador/servicios", name = "ServicioPadreId")
    public JAXBElement<String> createServicioPadreId(String value) {
        return new JAXBElement<String>(_ServicioPadreId_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigInteger }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://softwaresci.com/ceet/contabilizador/servicios", name = "ActoId")
    public JAXBElement<BigInteger> createActoId(BigInteger value) {
        return new JAXBElement<BigInteger>(_ActoId_QNAME, BigInteger.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://softwaresci.com/ceet/contabilizador/servicios", name = "IndicadorEspecial")
    public JAXBElement<String> createIndicadorEspecial(String value) {
        return new JAXBElement<String>(_IndicadorEspecial_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://softwaresci.com/ceet/contabilizador/servicios", name = "AnoRenova")
    public JAXBElement<String> createAnoRenova(String value) {
        return new JAXBElement<String>(_AnoRenova_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://softwaresci.com/ceet/contabilizador/servicios", name = "Servicio")
    public JAXBElement<String> createServicio(String value) {
        return new JAXBElement<String>(_Servicio_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://softwaresci.com/ceet/contabilizador/servicios", name = "GastoAdministrativo")
    public JAXBElement<String> createGastoAdministrativo(String value) {
        return new JAXBElement<String>(_GastoAdministrativo_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://softwaresci.com/ceet/contabilizador/servicios", name = "NumMatricula")
    public JAXBElement<String> createNumMatricula(String value) {
        return new JAXBElement<String>(_NumMatricula_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigInteger }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://softwaresci.com/ceet/contabilizador/servicios", name = "Item")
    public JAXBElement<BigInteger> createItem(BigInteger value) {
        return new JAXBElement<BigInteger>(_Item_QNAME, BigInteger.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigInteger }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://softwaresci.com/ceet/contabilizador/servicios", name = "ValorBase")
    public JAXBElement<BigInteger> createValorBase(BigInteger value) {
        return new JAXBElement<BigInteger>(_ValorBase_QNAME, BigInteger.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://softwaresci.com/ccb/pupx/dto", name = "Mensaje")
    public JAXBElement<String> createMensaje(String value) {
        return new JAXBElement<String>(_Mensaje_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://softwaresci.com/ccb/pupx/dto", name = "ErrorId")
    public JAXBElement<String> createErrorId(String value) {
        return new JAXBElement<String>(_ErrorId_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://softwaresci.com/ceet/contabilizador/servicios", name = "Matricula")
    public JAXBElement<String> createMatricula(String value) {
        return new JAXBElement<String>(_Matricula_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigInteger }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://softwaresci.com/ceet/contabilizador/servicios", name = "ValorTotal")
    public JAXBElement<BigInteger> createValorTotal(BigInteger value) {
        return new JAXBElement<BigInteger>(_ValorTotal_QNAME, BigInteger.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://softwaresci.com/ceet/contabilizador/servicios", name = "FechaBase")
    public JAXBElement<String> createFechaBase(String value) {
        return new JAXBElement<String>(_FechaBase_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://softwaresci.com/ceet/contabilizador/servicios", name = "ServicioId")
    public JAXBElement<String> createServicioId(String value) {
        return new JAXBElement<String>(_ServicioId_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://softwaresci.com/ceet/contabilizador/servicios", name = "FechaDocumentobroId")
    public JAXBElement<String> createFechaDocumentobroId(String value) {
        return new JAXBElement<String>(_FechaDocumentobroId_QNAME, String.class, null, value);
    }

}
