//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.2-147 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.06.08 at 01:52:41 PM COT 
//


package com.ccb.simasc.transversal.dto.pup.generado;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{http://softwaresci.com/ceet/contabilizador/servicios}RealizarLiquidacionResult"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "realizarLiquidacionResult"
})
@XmlRootElement(name = "RealizarLiquidacionResponse")
public class RealizarLiquidacionResponse {

    @XmlElement(name = "RealizarLiquidacionResult", required = true)
    protected RealizarLiquidacionResult realizarLiquidacionResult;

    /**
     * Gets the value of the realizarLiquidacionResult property.
     * 
     * @return
     *     possible object is
     *     {@link RealizarLiquidacionResult }
     *     
     */
    public RealizarLiquidacionResult getRealizarLiquidacionResult() {
        return realizarLiquidacionResult;
    }

    /**
     * Sets the value of the realizarLiquidacionResult property.
     * 
     * @param value
     *     allowed object is
     *     {@link RealizarLiquidacionResult }
     *     
     */
    public void setRealizarLiquidacionResult(RealizarLiquidacionResult value) {
        this.realizarLiquidacionResult = value;
    }

}
