//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.2-147 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.06.08 at 01:52:41 PM COT 
//


package com.ccb.simasc.transversal.dto.pup.generado;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{http://softwaresci.com/ccb/pupx/dto}Detalle"/>
 *         &lt;element ref="{http://softwaresci.com/ccb/pupx/dto}ErrorId"/>
 *         &lt;element ref="{http://softwaresci.com/ccb/pupx/dto}Mensaje"/>
 *         &lt;element ref="{http://softwaresci.com/ccb/pupx/dto}MonedaId"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "detalle",
    "errorId",
    "mensaje",
    "monedaId"
})
@XmlRootElement(name = "RealizarLiquidacionResult")
public class RealizarLiquidacionResult {

    @XmlElement(name = "Detalle", namespace = "http://softwaresci.com/ccb/pupx/dto", required = true)
    protected Detalle detalle;
    @XmlElement(name = "ErrorId", namespace = "http://softwaresci.com/ccb/pupx/dto", required = true, nillable = true)
    protected String errorId;
    @XmlElement(name = "Mensaje", namespace = "http://softwaresci.com/ccb/pupx/dto", required = true, nillable = true)
    protected String mensaje;
    @XmlElement(name = "MonedaId", namespace = "http://softwaresci.com/ccb/pupx/dto", required = true)
    protected String monedaId;

    /**
     * Gets the value of the detalle property.
     * 
     * @return
     *     possible object is
     *     {@link Detalle }
     *     
     */
    public Detalle getDetalle() {
        return detalle;
    }

    /**
     * Sets the value of the detalle property.
     * 
     * @param value
     *     allowed object is
     *     {@link Detalle }
     *     
     */
    public void setDetalle(Detalle value) {
        this.detalle = value;
    }

    /**
     * Gets the value of the errorId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getErrorId() {
        return errorId;
    }

    /**
     * Sets the value of the errorId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setErrorId(String value) {
        this.errorId = value;
    }

    /**
     * Gets the value of the mensaje property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMensaje() {
        return mensaje;
    }

    /**
     * Sets the value of the mensaje property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMensaje(String value) {
        this.mensaje = value;
    }

    /**
     * Gets the value of the monedaId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMonedaId() {
        return monedaId;
    }

    /**
     * Sets the value of the monedaId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMonedaId(String value) {
        this.monedaId = value;
    }

}
